global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_app_1'
    static_configs:
      - targets: ['django1:8001']

  - job_name: 'django_app_2'
    static_configs:
      - targets: ['django2:8002']

  - job_name: 'django_app_3'
    static_configs:
      - targets: ['django3:8003']
